spring:
  application:
    name: Tabula_BE
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
#      auto-index-creation: true
  config:
    import: optional:file:.env[.properties]
